apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  project: default
  source:
    repoURL: git@github.com:paulbrittain/argocd.git
    path: applications
    targetRevision: HEAD
  destination:
    server: https://192.168.178.89:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
