apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: core
spec:
  project: default
  source:
    repoURL: git@github.com:paulbrittain/argocd.git
    path: configurations/nginx
    targetRevision: HEAD
  destination:
    server: https://192.168.178.89:6443
    namespace: core
  syncPolicy:
    automated:
      selfHeal: true