apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:paulbrittain/argocd.git
    path: configurations/overseerr
    targetRevision: HEAD
  destination:
    server: https://192.168.178.89:6443
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
