apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-ingress-local
  namespace: core
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /overseerr(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              number: 80
