apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-nfs-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: overseerr-nfs-pv